version: 2

jobs:
  publish:
    docker:
      - image: circleci/node:10.15
    working_directory: ~/website/website
    steps:
      - checkout:
          path: ~/website

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: |
            yarn install

      - run:
          name: Publish website
          command: |
            echo "machine github.com login marconi1992 password $GITHUB_TOKEN" > ~/.netrc
            GIT_USER=marconi1992 yarn publish-gh-pages

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

workflows:
  version: 2
  main:
    jobs:
      - publish:
          filters:
            branches:
              only: master




